### ISSUE TITLE
Document renderer

### ISSUE THREAD

**Issue by Brownshome** [AGS-Programming-Club/AGS-Game-Project#14]

**Comment by andrewcchen** [comment]
why?

**Comment by Brownshome** [comment]
Because it needs to be documented so people can use it

**Comment by andrewcchen** [comment]
Oh, I thought you want to render PDF or something

**Comment by Brownshome** [comment]
no god no, I am not that crazy

**Comment by Brownshome** [comment]
Done in d5c22ae2bd17f2f945a7ec650f8fe84f9402a14f
