### ISSUE TITLE
New directory structure

### ISSUE THREAD

**Issue by andrewcchen** [AGS-Programming-Club/AGS-Game-Project#5]
I propose the following a directory structure (explanation below):

```
.
├── client/
│   ├── include/
│   │   └── a_module/
│   │       └── an_api.hpp
│   ├── res/
│   │   └── a_resource.bmp
│   ├── src/
│   │   ├── a_module/
│   │   │   └── a.cpp
│   │   └── main/
│   │       └── main.cpp
│   └── test/
│       ├── a_module/
│       │   └── a.cpp
│       └── main/
│           └── main.cpp
├── common/
│   ├── include/
│   │   └── a_module/
│   │       └── an_api.hpp
│   ├── src/
│   │   └── a_module/
│   └── test/
│       └── a_module/
├── server/
│   └── ... (same as client)
└── Readme.md
```

The include directory in client contains the APIs (header files) that are used in between the modules in client. (and it is the same for server)
The include directory in common contains the APIs that are used by both client and server.
The source files and module-internal header files go inside src/, unit/integration tests go inside test/.

Please tell me what do you think about this.

**Comment by clisamurai** [comment]
Great.
